import type {
  Violation,
  ViolationItem,
  WorkOrder,
  Photo,
  Profile,
  Organization,
} from '@/lib/types';

export const mockOrganization = (overrides: Partial<Organization> = {}): Organization => ({
  id: 'org-123',
  name: 'Test Property Management',
  slug: 'test-properties',
  plan: 'professional',
  settings: {},
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  ...overrides,
});

export const mockProfile = (overrides: Partial<Profile> = {}): Profile => ({
  id: 'user-123',
  org_id: 'org-123',
  full_name: 'Test User',
  email: 'test@example.com',
  role: 'PROJECT_MANAGER',
  phone: null,
  avatar_url: null,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  ...overrides,
});

export const mockViolation = (overrides: Partial<Violation> = {}): Violation => ({
  id: 'v-123',
  org_id: 'org-123',
  property_id: 'prop-123',
  notice_id: '24NOIR-INS-12345',
  respondent: 'Test Property LLC',
  infraction_address: '123 Main St NW, Washington, DC',
  date_of_service: '2024-01-15',
  total_fines: 5000,
  status: 'PARSED',
  priority: 2,
  abatement_deadline: '2024-03-15',
  assigned_to: null,
  pdf_storage_path: 'uploads/test.pdf',
  parse_status: 'complete',
  parse_metadata: {},
  raw_ai_output: null,
  source: 'upload',
  notes: null,
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-01-15T10:00:00Z',
  ...overrides,
});

export const mockViolationItem = (overrides: Partial<ViolationItem> = {}): ViolationItem => ({
  id: 'item-123',
  org_id: 'org-123',
  violation_id: 'v-123',
  item_number: 1,
  violation_code: 'IPMC-502.1',
  priority: 2,
  abatement_deadline: '60 Days',
  fine: 500,
  violation_description: 'Failure to maintain ceiling in habitable condition',
  specific_location: 'Unit 201',
  floor_number: '2',
  date_of_infraction: '2024-01-10',
  time_of_infraction: '14:30',
  task_description: 'Repair ceiling damage and paint',
  status: 'open',
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-01-15T10:00:00Z',
  ...overrides,
});

export const mockWorkOrder = (overrides: Partial<WorkOrder> = {}): WorkOrder => ({
  id: 'wo-123',
  org_id: 'org-123',
  violation_id: 'v-123',
  assigned_to: null,
  contractor_name: 'Alex Contractor',
  contractor_email: 'alex@contractor.com',
  contractor_phone: '+1-202-555-0100',
  status: 'ASSIGNED',
  due_date: '2024-03-01',
  notes: 'Please prioritize Unit 201 ceiling repair',
  completed_at: null,
  created_at: '2024-01-16T09:00:00Z',
  updated_at: '2024-01-16T09:00:00Z',
  ...overrides,
});

export const mockPhoto = (overrides: Partial<Photo> = {}): Photo => ({
  id: 'photo-123',
  org_id: 'org-123',
  violation_id: 'v-123',
  violation_item_id: 'item-123',
  photo_type: 'INSPECTOR',
  storage_path: 'uploads/test.pdf',
  file_name: 'page_3.pdf',
  file_size: 45000,
  mime_type: 'image/jpeg',
  page_number: 3,
  matched_violation_code: 'IPMC-502.1',
  status: 'APPROVED',
  approved_by: null,
  approved_at: null,
  rejection_reason: null,
  taken_at: null,
  metadata: { description: 'Ceiling damage visible' },
  created_at: '2024-01-15T10:05:00Z',
  updated_at: '2024-01-15T10:05:00Z',
  ...overrides,
});

export const mockContractorToken = (overrides: Partial<any> = {}) => ({
  id: 'token-123',
  org_id: 'org-123',
  work_order_id: 'wo-123',
  token: 'abc-123-def-456',
  contractor_name: 'Alex Contractor',
  contractor_email: 'alex@contractor.com',
  contractor_phone: '+1-202-555-0100',
  expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),  // 30 days from now
  revoked_at: null,
  last_accessed_at: null,
  created_by: 'user-123',
  created_at: '2024-01-16T09:00:00Z',
  ...overrides,
});
